apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: main-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
  workspaces:
  - name: pipeline-pvc
  tasks:  
    - name: build-task
      taskRef:
        name: build-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc 
    - name: wait-for-tests
      runAfter: [build-task]
      taskRef:
        name: iam-call-pipeline-by-cfgmap
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
      params:
      - name: target-pipeline-id-name
        value: DEV_DEPLOY_TARGET_PIPELINE_ID
      - name: task-cfgmap
        value: call-deploy-pipeline
      - name: target-pipeline-id
        value: "15a887a0-c0b1-4a26-975f-3407c4b585a0"
      - name: event-listener
        value: "\"test-listener\""
    - name: deploy
      runAfter: [wait-for-tests]
      taskRef:
        name: deploy
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: wait-for-deploy
      runAfter: [deploy]
      taskRef:
        name: wait-for-deploy
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: cleanup
      runAfter: [wait-for-deploy]
      taskRef:
        name: cleanup
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
