apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: briantester-vault
spec:
  provider:
    vault:
      server: "https://vserv-test.sos.ibm.com:8200"
      path: ""
      version: "v1"
      auth:
        appRole:
          path: "approle"
          roleId: ""
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "secure-properties"
            key: "hv-key"
