## External Secret (base): briantester-hv-secret.yaml
# See Kustomize reference for guides and examples
# https://kubectl.docs.kubernetes.io/references/kustomize/

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: briantester-hv-extscrt
spec:
  secretStoreRef:
    name: briantester-hv
    kind: SecretStore
  refreshInterval: 0s
  target:
    name: briantester-hv-extscrt
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: hv1
      remoteRef:
        key: generic/project/otc-setup/disconnected-agent/repoGithubToken
        property: token
