apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: cluster
      description: the cluster
    - name: anothervalu
      description: the valu
    - name: localrun_aes_key
      description: localrun_aes_key
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: deploy
      image: ubuntu
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
        - name: ANOTHERV
          value: $(params.anothervalu)
        - name: LOCALRUN
          value: $(params.localrun_aes_key)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Hey $LOCALRUN"
          echo "Deploying to $CLUSTER";
          echo "Oh and $ANOTHERV";
          apt update
          apt install -y git
          git clone https://github.com/bogg/subpipeline.git
