apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: deploy-pipeline
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: deploy-listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
