apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
    - name: cluster
      description: the cluster
  workspaces:
  - name: task-pvc
    mountPath: /artifacts  
  steps:
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - ./script.sh
