apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
    - name: cluster
      description: the cluster
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: jerh-noop
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Hi Jerh!"
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Deploying to $CLUSTER"
          echo "Small Pause!";
          echo "Done!";
          env;
          env;
          env;
          for i in {1..2} ; do
          echo "Round $i";
          ls;
          done
    - name: deploy2
      image: thebog/privatebogo:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Deploying to $CLUSTER"
          ls;
          ls;
          env;
          echo "Small Pause!";
          echo "Done!";
          for i in {1..2} ; do
          echo "Round $i";
          sleep 10s;
          ls;
          done
