apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: cluster
      description: the cluster
    - name: anothervalu
      description: the valu
    - name: localrun_aes_key
      description: localrun_aes_key
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
        - name: ANOTHERV
          value: $(params.anothervalu)
        - name: LOCALRUN
          value: $(params.localrun_aes_key)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail;
          echo "Hey $LOCALRUN"
          echo "Deploying to $CLUSTER";
      
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_core_git_clone_time_summary":{"ibm_toolchain_pipeline_devsecops_time":"124","ibm_toolchain_pipeline_version":"v11","ibm_toolchain_pipeline_type":"ci"}}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_core_change_request_process_time_summary":{"ibm_toolchain_pipeline_devsecops_time":"165961","value":"7"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_core_pipeline_evaluation_time_summary":{"ibm_toolchain_pipeline_devsecops_time":"165961","ibm_toolchain_pipeline_devsecops_pipeline_type":"pr","value":"7"}'; 
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_pipeline_info":{"ibm_toolchain_pipeline_devsecops_branch":"fix/v10-master-image-update","ibm_toolchain_pipeline_devsecops_pipeline_type":"ci", "value":"1"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_artifact_upload_time_summary":{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_locker_evidence_summary_time_summary": { "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_locker_evidence_publish_time_summary": { "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_inventory_get_time_summary": { "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_commands_count": {"value": "1"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_commands_success_count": {"value": "1"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_commands_error_count": {"value": "1"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_api_calls_count": {"value": "1"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_github_api_calls_count": {"value": "1"}';
          echo '::debug::{"ibm_toolchain_pipeline_devsecops_cli_cos_api_call_count":{"value": "1"}';
          
          echo "Oh and $ANOTHERV";
          echo "Small Pause!";
          sleep 5s;
          echo "Done!";
          for i in {1..3} ; do
          echo "Round $i";
          ls;
          sleep 5s;
          done
