apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  steps:
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Deploying to bog";
          sleep 1m;
          echo "Small Pause!";
          sleep 1m;
          echo "Done!";
          for i in {1..2} ; do
          echo "Round $i";
          ls;
          sleep 5s;
          done
