apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  inputs:
    params:
      - name: sshKeySecret
        description: The name of the Kubernetes secret containing the SSH private key.
  steps:
    - name: git-clone
      image: ubuntu
      command: ["sh"]
      args:
        - "-c"
        - |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone git@github.ibm.com:STGAutomation/provisioning.git /workspace/repo
      env:
        - name: SSH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: ssh-private-key
