# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  labels:
    cdtest: bog
  disableNameSuffixHash: true


configMapGenerator:
- name: environment-properties
  env: configs.env

secretGenerator:
  - name: secure-properties-file
    files:
      - secrets.env
    type: Opaque

  - name: secure-properties-env
    env: secrets.env
    type: Opaque

  - name: registry-creds
    files:
      - dockersecret.json
    type: kubernetes.io/dockerconfigjson